[package]
name = "mullvad"
version = "0.1.0"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
rofi-plugin = { path = "../../" }
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"
